name: online_shopping
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_boxicons: ^3.0.0
  image_picker: ^1.1.1



   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2 
  fluttertoast: ^8.0.7
  animated_search_bar: ^2.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/loginPage.jpg
  